name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4', '8.5']
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer validate

      - uses: ramsey/composer-install@v4
        with:
          composer-options: "--prefer-dist"

      - run: composer show

      - run: composer unit
